from coordinator_agent import CoordinatorAgent
from datetime import datetime

if __name__ == "__main__":
    print("="*60)
    print("Prelytics Business Intelligence System")
    print("="*60)

    company_name = input("Enter company name: ")
    company_url = input("Enter company website URL: ")

    print(f"\nAnalyzing {company_name}...")

    try:
        agent = CoordinatorAgent(company_name, company_url)
        results = agent.run_workflow()

        # Ask if user wants to save the report
        save_option = input(
            "\nWould you like to save this report to a file? (y/n): ").lower().strip()

        if save_option in ['y', 'yes']:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"{company_name}_Business_Intelligence_Report_{timestamp}.txt"

            with open(filename, 'w', encoding='utf-8') as f:
                f.write(f"BUSINESS INTELLIGENCE REPORT\n")
                f.write(f"Company: {company_name}\n")
                f.write(
                    f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"{'='*60}\n\n")
                f.write(results)
                f.write(f"\n{'='*60}\n")
                f.write(
                    "Report generated by Prelytics Business Intelligence System\n")

            print(f"✅ Report saved to: {filename}")

        print("\n🎉 Analysis complete!")

    except Exception as e:
        print(f"❌ Error during analysis: {str(e)}")
        print("Please check your API keys and internet connection.")
